from __future__ import annotations
from typing import List, Tuple
from .combat import attackable_creature_powers, attackable_tokens, max_creature_power
from .index import CardIndex
from .models import GameState
from .tokens import estimate_tokens_created_from_text


def has_creature_tap_mana_enabler(st: GameState, idx: CardIndex) -> bool:
    return any("CreatureTapManaEnabler" in idx.roles(c) for c in st.battlefield)


def compute_creature_tap_mana_pool(st: GameState, idx: CardIndex) -> Tuple[List[int], int]:
    creature_powers = attackable_creature_powers(st, idx)
    creature_powers.sort()
    tok = attackable_tokens(st, idx)
    return creature_powers, tok


def burst_mana_from_creatures_if_available(st: GameState, idx: CardIndex) -> int:
    # find any permanent that has the burst role and can tap this turn
    candidates = [c for c in st.battlefield if "BurstManaFromCreatures" in idx.roles(c)]
    if not candidates:
        return 0

    # conservative: only count if at least one such creature is “ready” this turn
    from .combat import attackable_creature_powers, attackable_tokens
    powers = attackable_creature_powers(st, idx)
    if not powers:
        return 0

    tok = attackable_tokens(st, idx)
    # X = other creatures you control (rough). We use attackable counts to keep it conservative.
    other = max(0, (len(powers) + tok) - 1)
    return other


def default_cast_policy(
        st: GameState,
        idx: CardIndex,
        available_mana: int,
        tap_creature_powers: List[int],
        tap_tokens: int,
        burst_mana: int,
) -> Tuple[int, List[int], int, int]:
    """
    Casting policy with creature-tap mana support.

    available_mana: "static" mana (lands + rocks/dorks counter)
    tap_creature_powers/tap_tokens: mana generated by tapping bodies (1 each)
    burst_mana: one-shot burst if Brigid-back is available (usually 0)

    Returns updated (available_mana, tap_creature_powers, tap_tokens, burst_mana).
    """

    def has_role(card: str, role: str) -> bool:
        return role in idx.roles(card)

    def mana_now() -> int:
        return available_mana + burst_mana + len(tap_creature_powers) + tap_tokens

    def eff_cost(card: str, mana_total: int) -> int:
        name = (card or "").strip().lower()
        if name == "finale of devastation":
            return 12 if mana_total >= 12 else 10_000
        return int(idx.mv(card))

    def pay(cost: int) -> bool:
        nonlocal available_mana, tap_creature_powers, tap_tokens, burst_mana

        if cost <= available_mana:
            available_mana -= cost
            return True

        need = cost - available_mana
        available_mana = 0

        if burst_mana > 0 and need > 0:
            use = min(need, burst_mana)
            burst_mana -= use
            need -= use
            if use > 0:
                st.brigid_tapped_for_mana = True

        while need > 0 and tap_creature_powers:
            tap_creature_powers.pop(0)
            st.creatures_tapped_for_mana += 1
            need -= 1

        if need > 0 and tap_tokens > 0:
            use_tok = min(need, tap_tokens)
            tap_tokens -= use_tok
            st.tokens_tapped_for_mana += use_tok
            need -= use_tok

        return need <= 0

    while True:
        total = mana_now()
        castable = [c for c in st.hand if (not idx.is_land(c)) and eff_cost(c, total) <= total]
        if not castable:
            break

        def prio(c: str):
            name = (c or "").strip().lower()
            if has_role(c, "Ramp"):
                return (1, idx.mv(c))
            if has_role(c, "DrawEngine"):
                return (2, idx.mv(c))
            if has_role(c, "Refill"):
                return (3, idx.mv(c))
            if has_role(c, "TokenMaker") or has_role(c, "TokenBurst"):
                return (4, idx.mv(c))
            if name in ("overwhelming stampede", "finale of devastation") or has_role(c, "Finisher"):
                return (5, idx.mv(c))
            return (9, idx.mv(c))

        castable.sort(key=prio)
        c = castable[0]
        name = (c or "").strip().lower()
        cost = eff_cost(c, total)

        if not pay(cost):
            break

        st.hand.remove(c)

        f = idx.facts(c)
        is_perm = bool(f and not (f.is_instant or f.is_sorcery))
        if is_perm:
            st.battlefield.add(c)
            st.entered_turn[c] = st.turn

        # Ramp: do NOT increment for creature-tap enablers
        if has_role(c, "Ramp") and ("CreatureTapManaEnabler" not in idx.roles(c)):
            st.ramp_sources_in_play += 1
            if f and f.is_artifact and not f.is_creature and not f.is_land:
                available_mana += 1

        # Refill
        if has_role(c, "Refill"):
            st.refills_resolved += 1
            for _ in range(2):
                if st.library:
                    st.hand.append(st.library.pop(0))

        # Tokens (rough)
        if (has_role(c, "TokenBurst") or has_role(c, "TokenMaker")) and f:
            created = estimate_tokens_created_from_text(f.oracle_text)
            if created > 0:
                st.token_pool += created
                st.tokens_created_this_turn += created

        # Finale finisher mode (X>=10)
        if name == "finale of devastation":
            st.finisher_boost = max(st.finisher_boost, 10)
            st.finisher_haste = True

        # Stampede
        if name == "overwhelming stampede":
            x = max_creature_power(st, idx)
            st.finisher_boost = max(st.finisher_boost, x)
            st.finisher_trample = True

        # Generic finisher spell
        if has_role(c, "Finisher") and f and (f.is_instant or f.is_sorcery):
            st.finisher_boost = max(st.finisher_boost, 3)

    return available_mana, tap_creature_powers, tap_tokens, burst_mana